language: node_js
node_js:
- '4.0'
- '9.0'
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FN1/hBp/SXbZf6YhskjUhbKw98B7aT6dzHOnU+66zwiOtZAjf/ENCtwEWnv0Y/lTGa87L3OzGGWm23tuT24rkLn6tPtMOqcREFXe8RuGRe1dwXO06fF6KiP1Ryfjpx8Xyqo+gjwNk+f6sCGPTpI0v9qjUp1sCGiLKv5FYcYaV4zQlwbT4K1Ux2jxdIJRar9qyuUls5G+8mQ/PWPOhvWLgewri95MY95wojemRdmRQgI1nCNhxY1I860dgTXR6B79IA2ajYiGS/OCCUSTooqBK7f1l5Wb0qDXFFoUmEVAlpjgin99Qz3NFyJgl6XJejTJ8H40RfWXaQowsCINEiZ6T2x2M99LoeGr4Ae+OfEx/KfhF6pF/iKvDnjKkVDrDCbG0N7lj8NtYKubmnKctQ/5WWDKpt7wq+zb82WTq56SZvDLD0WUrudhAvZvw6XwcyT31vaEuJ4p/774GE0uriBy/FtFGC+8H57mLV3G1B6wUAwyE7bZhe4xTXfTBy2WobKJvpGAU5Vl+9Wz0A/pIVvVD8n/JVO7lpFx3cjcyIMTQeBI3f28XSi/BllUrijuCP0KjbXGfwu8yDdLXQCC69QzfvWoyjzGdYtQilZkPPHmB25ewwv54smwB+UOjcVodQgx60vrZ+e1mNvEpgLi/YbFgr6OnQ6mTGgIwYsXForiqwA=
  file:
    - "retext-profanities.js"
    - "retext-profanities.min.js"
  on:
    tags: true
    node: '9.0'
